### ISSUE TITLE
Feature request: Export video

### ISSUE THREAD

**Issue by batpad** [developmentseed/gl-director#3]
There seems to be some ability now to generate hi-res mp4 video from GL JS maps: https://github.com/mapbox/mapbox-gl-js/pull/10172

It would be super cool if we could add an option to export video here.

If this seems interesting, am happy to take a look.

**Comment by pratikyadav** [comment]
Seems interesting. 👍

**Comment by drewbo** [comment]
Closed via https://github.com/developmentseed/gl-director/pull/8
