### ISSUE TITLE
Camera bumps over terrain

### ISSUE THREAD

**Issue by davemaps** [developmentseed/gl-director#5]
When I generate a flyover using GL Director, it appears smooth. Yet when I export and download the generated code, the camera appears to bump along the terrain.

Here’s a screen capture of the animation in Director:
https://davemaps.com/assets/vid/mapbox-3d-flyover-campbell.mp4

And here’s the same scene once exported, demonstrating the “bumpy” camera:
https://campbell-river-flyover.glitch.me/

**Comment by davemaps** [comment]
Here’s the Glitch URL if you want to see the code:
https://glitch.com/edit/#!/campbell-river-flyover

**Comment by drewbo** [comment]
Thanks for the report @davemaps; we've included a bit of code in the app to prevent the bumpiness but looks like it isn't present in the export; we'll fix this up and let you know

**Comment by davemaps** [comment]
Thanks, @drewbo! For what it’s worth, I don’t get any bumpiness if I set the target to the same coordinates for the start and end of the animation.

**Comment by drewbo** [comment]
@davemaps fixed and new version should be up in a minute; let me know if the new export code works out for you (and thanks to @danielfdsilva for the fix)
